apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-5-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-5
  template:
    metadata:
      labels:
        app: docker-5
    spec:
      containers:
      - name: docker-5-container
        image: 045193383710.dkr.ecr.us-east-1.amazonaws.com/docker-5:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: springboot1secret
