apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-5-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-5
  template:
    metadata:
      labels:
        app: docker-5
    spec:
      containers:
      - name: docker-5-container
        image: mydocker1405/docker-5:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: springboot1secret
